export const dummyUser = {
  login: 'octocat',
  avatar_url: 'https://i.pravatar.cc/200?img=1',
  name: 'The Octocat',
  bio: 'A passionate full-stack developer building open-source tools for the community. Loves JavaScript, TypeScript, and contributing to meaningful projects.',
  public_repos: 42,
  followers: 8923,
  following: 127,
}

export const dummyRepos = [
  {
    id: 1,
    name: 'javascript-algorithms',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=1' },
    description: 'Classic algorithms and data structures implemented in JavaScript with detailed explanations.',
    language: 'JavaScript',
    stargazers_count: 84500,
    updated_at: '2026-05-28T14:32:00Z',
    default_branch: 'main',
    open_issues_count: 23,
    forks_count: 12400,
    license: { spdx_id: 'MIT' },
    watchers_count: 3200,
    created_at: '2022-03-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'react-component-library',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=2' },
    description: 'A collection of reusable, accessible React UI components with zero dependencies.',
    language: 'TypeScript',
    stargazers_count: 12300,
    updated_at: '2026-05-25T09:15:00Z',
    default_branch: 'main',
    open_issues_count: 8,
    forks_count: 2100,
    license: { spdx_id: 'MIT' },
    watchers_count: 980,
    created_at: '2023-06-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'go-microservices',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=3' },
    description: 'Production-ready microservices template in Go with gRPC, tracing, and Docker Compose.',
    language: 'Go',
    stargazers_count: 6700,
    updated_at: '2026-05-22T16:45:00Z',
    default_branch: 'master',
    open_issues_count: 15,
    forks_count: 890,
    license: { spdx_id: 'Apache-2.0' },
    watchers_count: 450,
    created_at: '2023-09-10T12:00:00Z',
  },
  {
    id: 4,
    name: 'python-ml-toolkit',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=4' },
    description: 'Machine learning utilities for data preprocessing, feature engineering, and model evaluation.',
    language: 'Python',
    stargazers_count: 4100,
    updated_at: '2026-05-18T11:20:00Z',
    default_branch: 'main',
    open_issues_count: 5,
    forks_count: 620,
    license: { spdx_id: 'BSD-3-Clause' },
    watchers_count: 310,
    created_at: '2023-11-22T14:00:00Z',
  },
  {
    id: 5,
    name: 'rust-cli-tools',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=5' },
    description: 'Fast and ergonomic CLI utilities built with Rust, focusing on developer productivity.',
    language: 'Rust',
    stargazers_count: 2800,
    updated_at: '2026-05-15T08:30:00Z',
    default_branch: 'main',
    open_issues_count: 3,
    forks_count: 340,
    license: { spdx_id: 'MIT' },
    watchers_count: 180,
    created_at: '2024-01-05T09:00:00Z',
  },
  {
    id: 6,
    name: 'dotfiles',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=6' },
    description: null,
    language: 'Shell',
    stargazers_count: 890,
    updated_at: '2026-05-10T19:00:00Z',
    default_branch: 'main',
    open_issues_count: 1,
    forks_count: 120,
    license: null,
    watchers_count: 45,
    created_at: '2022-08-12T07:00:00Z',
  },
  {
    id: 7,
    name: 'rails-api-boilerplate',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=7' },
    description: 'A modern Rails API starter with JWT auth, serializers, and RSpec test suite.',
    language: 'Ruby',
    stargazers_count: 1200,
    updated_at: '2026-04-28T13:10:00Z',
    default_branch: 'main',
    open_issues_count: 7,
    forks_count: 210,
    license: { spdx_id: 'MIT' },
    watchers_count: 90,
    created_at: '2024-02-18T11:00:00Z',
  },
  {
    id: 8,
    name: 'learning-cpp',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=8' },
    description: 'My journey learning C++ — examples, exercises, and mini-projects.',
    language: 'C++',
    stargazers_count: 340,
    updated_at: '2026-03-20T15:40:00Z',
    default_branch: 'main',
    open_issues_count: 0,
    forks_count: 85,
    license: null,
    watchers_count: 22,
    created_at: '2024-05-30T16:00:00Z',
  },
  {
    id: 1,
    name: 'javascript-algorithms',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=1' },
    description: 'Classic algorithms and data structures implemented in JavaScript with detailed explanations.',
    language: 'JavaScript',
    stargazers_count: 84500,
    updated_at: '2026-05-28T14:32:00Z',
    default_branch: 'main',
    open_issues_count: 23,
    forks_count: 12400,
    license: { spdx_id: 'MIT' },
    watchers_count: 3200,
    created_at: '2022-03-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'react-component-library',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=2' },
    description: 'A collection of reusable, accessible React UI components with zero dependencies.',
    language: 'TypeScript',
    stargazers_count: 12300,
    updated_at: '2026-05-25T09:15:00Z',
    default_branch: 'main',
    open_issues_count: 8,
    forks_count: 2100,
    license: { spdx_id: 'MIT' },
    watchers_count: 980,
    created_at: '2023-06-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'go-microservices',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=3' },
    description: 'Production-ready microservices template in Go with gRPC, tracing, and Docker Compose.',
    language: 'Go',
    stargazers_count: 6700,
    updated_at: '2026-05-22T16:45:00Z',
    default_branch: 'master',
    open_issues_count: 15,
    forks_count: 890,
    license: { spdx_id: 'Apache-2.0' },
    watchers_count: 450,
    created_at: '2023-09-10T12:00:00Z',
  },
  {
    id: 4,
    name: 'python-ml-toolkit',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=4' },
    description: 'Machine learning utilities for data preprocessing, feature engineering, and model evaluation.',
    language: 'Python',
    stargazers_count: 4100,
    updated_at: '2026-05-18T11:20:00Z',
    default_branch: 'main',
    open_issues_count: 5,
    forks_count: 620,
    license: { spdx_id: 'BSD-3-Clause' },
    watchers_count: 310,
    created_at: '2023-11-22T14:00:00Z',
  },
  {
    id: 5,
    name: 'rust-cli-tools',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=5' },
    description: 'Fast and ergonomic CLI utilities built with Rust, focusing on developer productivity.',
    language: 'Rust',
    stargazers_count: 2800,
    updated_at: '2026-05-15T08:30:00Z',
    default_branch: 'main',
    open_issues_count: 3,
    forks_count: 340,
    license: { spdx_id: 'MIT' },
    watchers_count: 180,
    created_at: '2024-01-05T09:00:00Z',
  },
  {
    id: 6,
    name: 'dotfiles',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=6' },
    description: null,
    language: 'Shell',
    stargazers_count: 890,
    updated_at: '2026-05-10T19:00:00Z',
    default_branch: 'main',
    open_issues_count: 1,
    forks_count: 120,
    license: null,
    watchers_count: 45,
    created_at: '2022-08-12T07:00:00Z',
  },
  {
    id: 7,
    name: 'rails-api-boilerplate',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=7' },
    description: 'A modern Rails API starter with JWT auth, serializers, and RSpec test suite.',
    language: 'Ruby',
    stargazers_count: 1200,
    updated_at: '2026-04-28T13:10:00Z',
    default_branch: 'main',
    open_issues_count: 7,
    forks_count: 210,
    license: { spdx_id: 'MIT' },
    watchers_count: 90,
    created_at: '2024-02-18T11:00:00Z',
  },
  {
    id: 8,
    name: 'learning-cpp',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=8' },
    description: 'My journey learning C++ — examples, exercises, and mini-projects.',
    language: 'C++',
    stargazers_count: 340,
    updated_at: '2026-03-20T15:40:00Z',
    default_branch: 'main',
    open_issues_count: 0,
    forks_count: 85,
    license: null,
    watchers_count: 22,
    created_at: '2024-05-30T16:00:00Z',
  },
  {
    id: 1,
    name: 'javascript-algorithms',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=1' },
    description: 'Classic algorithms and data structures implemented in JavaScript with detailed explanations.',
    language: 'JavaScript',
    stargazers_count: 84500,
    updated_at: '2026-05-28T14:32:00Z',
    default_branch: 'main',
    open_issues_count: 23,
    forks_count: 12400,
    license: { spdx_id: 'MIT' },
    watchers_count: 3200,
    created_at: '2022-03-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'react-component-library',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=2' },
    description: 'A collection of reusable, accessible React UI components with zero dependencies.',
    language: 'TypeScript',
    stargazers_count: 12300,
    updated_at: '2026-05-25T09:15:00Z',
    default_branch: 'main',
    open_issues_count: 8,
    forks_count: 2100,
    license: { spdx_id: 'MIT' },
    watchers_count: 980,
    created_at: '2023-06-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'go-microservices',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=3' },
    description: 'Production-ready microservices template in Go with gRPC, tracing, and Docker Compose.',
    language: 'Go',
    stargazers_count: 6700,
    updated_at: '2026-05-22T16:45:00Z',
    default_branch: 'master',
    open_issues_count: 15,
    forks_count: 890,
    license: { spdx_id: 'Apache-2.0' },
    watchers_count: 450,
    created_at: '2023-09-10T12:00:00Z',
  },
  {
    id: 4,
    name: 'python-ml-toolkit',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=4' },
    description: 'Machine learning utilities for data preprocessing, feature engineering, and model evaluation.',
    language: 'Python',
    stargazers_count: 4100,
    updated_at: '2026-05-18T11:20:00Z',
    default_branch: 'main',
    open_issues_count: 5,
    forks_count: 620,
    license: { spdx_id: 'BSD-3-Clause' },
    watchers_count: 310,
    created_at: '2023-11-22T14:00:00Z',
  },
  {
    id: 5,
    name: 'rust-cli-tools',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=5' },
    description: 'Fast and ergonomic CLI utilities built with Rust, focusing on developer productivity.',
    language: 'Rust',
    stargazers_count: 2800,
    updated_at: '2026-05-15T08:30:00Z',
    default_branch: 'main',
    open_issues_count: 3,
    forks_count: 340,
    license: { spdx_id: 'MIT' },
    watchers_count: 180,
    created_at: '2024-01-05T09:00:00Z',
  },
  {
    id: 6,
    name: 'dotfiles',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=6' },
    description: null,
    language: 'Shell',
    stargazers_count: 890,
    updated_at: '2026-05-10T19:00:00Z',
    default_branch: 'main',
    open_issues_count: 1,
    forks_count: 120,
    license: null,
    watchers_count: 45,
    created_at: '2022-08-12T07:00:00Z',
  },
  {
    id: 7,
    name: 'rails-api-boilerplate',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=7' },
    description: 'A modern Rails API starter with JWT auth, serializers, and RSpec test suite.',
    language: 'Ruby',
    stargazers_count: 1200,
    updated_at: '2026-04-28T13:10:00Z',
    default_branch: 'main',
    open_issues_count: 7,
    forks_count: 210,
    license: { spdx_id: 'MIT' },
    watchers_count: 90,
    created_at: '2024-02-18T11:00:00Z',
  },
  {
    id: 8,
    name: 'learning-cpp',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=8' },
    description: 'My journey learning C++ — examples, exercises, and mini-projects.',
    language: 'C++',
    stargazers_count: 340,
    updated_at: '2026-03-20T15:40:00Z',
    default_branch: 'main',
    open_issues_count: 0,
    forks_count: 85,
    license: null,
    watchers_count: 22,
    created_at: '2024-05-30T16:00:00Z',
  },
  {
    id: 1,
    name: 'javascript-algorithms',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=1' },
    description: 'Classic algorithms and data structures implemented in JavaScript with detailed explanations.',
    language: 'JavaScript',
    stargazers_count: 84500,
    updated_at: '2026-05-28T14:32:00Z',
    default_branch: 'main',
    open_issues_count: 23,
    forks_count: 12400,
    license: { spdx_id: 'MIT' },
    watchers_count: 3200,
    created_at: '2022-03-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'react-component-library',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=2' },
    description: 'A collection of reusable, accessible React UI components with zero dependencies.',
    language: 'TypeScript',
    stargazers_count: 12300,
    updated_at: '2026-05-25T09:15:00Z',
    default_branch: 'main',
    open_issues_count: 8,
    forks_count: 2100,
    license: { spdx_id: 'MIT' },
    watchers_count: 980,
    created_at: '2023-06-01T08:00:00Z',
  },
  {
    id: 3,
    name: 'go-microservices',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=3' },
    description: 'Production-ready microservices template in Go with gRPC, tracing, and Docker Compose.',
    language: 'Go',
    stargazers_count: 6700,
    updated_at: '2026-05-22T16:45:00Z',
    default_branch: 'master',
    open_issues_count: 15,
    forks_count: 890,
    license: { spdx_id: 'Apache-2.0' },
    watchers_count: 450,
    created_at: '2023-09-10T12:00:00Z',
  },
  {
    id: 4,
    name: 'python-ml-toolkit',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=4' },
    description: 'Machine learning utilities for data preprocessing, feature engineering, and model evaluation.',
    language: 'Python',
    stargazers_count: 4100,
    updated_at: '2026-05-18T11:20:00Z',
    default_branch: 'main',
    open_issues_count: 5,
    forks_count: 620,
    license: { spdx_id: 'BSD-3-Clause' },
    watchers_count: 310,
    created_at: '2023-11-22T14:00:00Z',
  },
  {
    id: 5,
    name: 'rust-cli-tools',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=5' },
    description: 'Fast and ergonomic CLI utilities built with Rust, focusing on developer productivity.',
    language: 'Rust',
    stargazers_count: 2800,
    updated_at: '2026-05-15T08:30:00Z',
    default_branch: 'main',
    open_issues_count: 3,
    forks_count: 340,
    license: { spdx_id: 'MIT' },
    watchers_count: 180,
    created_at: '2024-01-05T09:00:00Z',
  },
  {
    id: 6,
    name: 'dotfiles',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=6' },
    description: null,
    language: 'Shell',
    stargazers_count: 890,
    updated_at: '2026-05-10T19:00:00Z',
    default_branch: 'main',
    open_issues_count: 1,
    forks_count: 120,
    license: null,
    watchers_count: 45,
    created_at: '2022-08-12T07:00:00Z',
  },
  {
    id: 7,
    name: 'rails-api-boilerplate',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=7' },
    description: 'A modern Rails API starter with JWT auth, serializers, and RSpec test suite.',
    language: 'Ruby',
    stargazers_count: 1200,
    updated_at: '2026-04-28T13:10:00Z',
    default_branch: 'main',
    open_issues_count: 7,
    forks_count: 210,
    license: { spdx_id: 'MIT' },
    watchers_count: 90,
    created_at: '2024-02-18T11:00:00Z',
  },
  {
    id: 8,
    name: 'learning-cpp',
    owner: { avatar_url: 'https://i.pravatar.cc/200?img=8' },
    description: 'My journey learning C++ — examples, exercises, and mini-projects.',
    language: 'C++',
    stargazers_count: 340,
    updated_at: '2026-03-20T15:40:00Z',
    default_branch: 'main',
    open_issues_count: 0,
    forks_count: 85,
    license: null,
    watchers_count: 22,
    created_at: '2024-05-30T16:00:00Z',
  }
]
